// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace NatLaRestTest.Demo.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("HTTP operations and assertions")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class HTTPOperationsAndAssertionsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "HTTP operations and assertions", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Http_Operations_and_Assertions.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
 await testRunner.GivenAsync("SSL certificate validation is disabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Http_Operations_and_Assertions.feature.ndjson", 9);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("HTTP create and fetch with JSONPath assertions")]
        public async global::System.Threading.Tasks.Task HTTPCreateAndFetchWithJSONPathAssertions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("HTTP create and fetch with JSONPath assertions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 9
 await testRunner.GivenAsync("the base URL \'$(demoApiBaseUrl)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
 await testRunner.WhenAsync("a random \'Word\' string is stored in variable \'newName\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
 await testRunner.AndAsync("a \'POST\' request to \'/objects\' is made with content type \'application/json\' and t" +
                        "he following request body:", "{\r\n\t\"name\": \"$(newName)\",\r\n\t\"data\": {\r\n\t\t\"year\": 2020,\r\n\t\t\"price\": 9.99,\r\n\t\t\"CPU " +
                        "model\": \"Z80\",\r\n\t\t\"Hard disk size\": \"1kB\"\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.ThenAsync("the response code equals \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
 await testRunner.AndAsync("the response indicates success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.WhenAsync("the response body is stored in variable \'created\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
 await testRunner.ThenAsync("the value of JSONPath \'$.name\' in variable \'created\' equals \'$(newName)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
 await testRunner.WhenAsync("the value of JSONPath \'$.id\' in variable \'created\' is stored in variable \'created" +
                        "Id\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
 await testRunner.ThenAsync("the value of variable \'createdId\' is not null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
 await testRunner.WhenAsync("a request to \'/objects/$(createdId)\' is made", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.AndAsync("a \'GET\' request to \'/objects/$(createdId)\' is made", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.ThenAsync("the response code equals \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
 await testRunner.AndAsync("the response code does not equal \'404\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("the response indicates success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.WhenAsync("the response body is stored in variable \'fetched\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
 await testRunner.ThenAsync("the value of JSONPath \'$.id\' in variable \'fetched\' equals \'$(createdId)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
 await testRunner.AndAsync("the value of JSONPath \'$.name\' in variable \'fetched\' contains \'$(newName)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("the value of JSONPath \'$.name\' in variable \'fetched\' does not equal \'Wrong Name\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.AndAsync("the value of JSONPath \'$.name\' in variable \'fetched\' is more than \'1\' characters " +
                        "long", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("the value of JSONPath \'$.name\' in variable \'fetched\' is not empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync("the value of JSONPath \'$.data\' in variable \'fetched\' contains \'CPU model\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.AndAsync("the value of JSONPath \'$.data.year\' in variable \'fetched\' is greater than \'2000\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
 await testRunner.AndAsync("the value of JSONPath \'$.data.price\' in variable \'fetched\' is less than \'100\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("HTTP create without explicit content type")]
        public async global::System.Threading.Tasks.Task HTTPCreateWithoutExplicitContentType()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("HTTP create without explicit content type", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 50
 await testRunner.GivenAsync("the base URL \'$(demoApiBaseUrl)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
 await testRunner.WhenAsync("a random \'Word\' string is stored in variable \'newName2\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
 await testRunner.AndAsync("a \'POST\' request to \'/objects\' is made with the following request body:", "{\r\n\t\"name\": \"$(newName2)\",\r\n\t\"data\": {\r\n\t\t\"year\": 2021,\r\n\t\t\"price\": 19.99\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.ThenAsync("the response indicates success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 63
 await testRunner.WhenAsync("the response body is stored in variable \'created2\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
 await testRunner.ThenAsync("the value of JSONPath \'$.name\' in variable \'created2\' equals \'$(newName2)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Showcase on POST /objects endpoint")]
        public async global::System.Threading.Tasks.Task ShowcaseOnPOSTObjectsEndpoint()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Showcase on POST /objects endpoint", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 68
 await testRunner.GivenAsync("the base URL \'$(demoApiBaseUrl)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
 await testRunner.WhenAsync("the value \'Apple MacBook Pro 16 (which was thrown out of a window)\' is stored in " +
                        "variable \'newName\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
 await testRunner.WhenAsync("a \'POST\' request to \'/objects\' is made with the following request body:", "{\r\n\t\"name\": \"$(newName)\",\r\n\t\"data\": {\r\n\t\t\"year\":2019,\r\n\t\t\"price\": 4999.99,\r\n\t\t\"CP" +
                        "U model\": \"Z80\",\r\n\t\t\"Hard disk size\": \"1kB\"\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
 await testRunner.ThenAsync("the response code equals \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 84
 await testRunner.AndAsync("the response indicates success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
 await testRunner.WhenAsync("the response body is stored in variable \'updatedEntity\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
 await testRunner.ThenAsync("the value of JSONPath \'$.name\' in variable \'updatedEntity\' equals \'$(newName)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Showcase on POST /objects endpoint (copy to show variable thing)")]
        public async global::System.Threading.Tasks.Task ShowcaseOnPOSTObjectsEndpointCopyToShowVariableThing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Showcase on POST /objects endpoint (copy to show variable thing)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 90
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 91
 await testRunner.GivenAsync("the base URL \'$(demoApiBaseUrl)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 93
 await testRunner.WhenAsync("the value \'NEW_NAME\' is stored in variable \'newName\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 94
 await testRunner.WhenAsync("a \'POST\' request to \'/objects\' is made with the following request body:", "{\r\n\t\"name\": \"$(newName)\",\r\n\t\"data\": {\r\n\t\t\"year\":2019,\r\n\t\t\"price\": 4999.99,\r\n\t\t\"CP" +
                        "U model\": \"Z80\",\r\n\t\t\"Hard disk size\": \"1kB\"\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 106
 await testRunner.ThenAsync("the response code equals \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 107
 await testRunner.AndAsync("the response indicates success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.WhenAsync("the response body is stored in variable \'updatedEntity\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
 await testRunner.ThenAsync("the value of JSONPath \'$.name\' in variable \'updatedEntity\' equals \'NEW_NAME\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Showcase on DELETE /objects endpoint")]
        public async global::System.Threading.Tasks.Task ShowcaseOnDELETEObjectsEndpoint()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Showcase on DELETE /objects endpoint", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 113
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 114
 await testRunner.GivenAsync("the base URL \'$(demoApiBaseUrl)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
 await testRunner.WhenAsync("a random \'Word\' string is stored in variable \'newName\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
 await testRunner.WhenAsync("a \'POST\' request to \'/objects\' is made with the following request body:", "{\r\n\t\"name\": \"$(newName)\",\r\n\t\"data\": {\r\n\t\t\"year\":2019,\r\n\t\t\"price\": 4999.99,\r\n\t\t\"CP" +
                        "U model\": \"Z80\",\r\n\t\t\"Hard disk size\": \"1kB\"\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
 await testRunner.ThenAsync("the response indicates success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 129
 await testRunner.WhenAsync("the response body is stored in variable \'createResult\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 130
 await testRunner.WhenAsync("the value of JSONPath \'$.id\' in variable \'createResult\' is stored in variable \'cr" +
                        "eatedId\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 132
 await testRunner.WhenAsync("a \'DELETE\' request to \'/objects/$(createdId)\' is made", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
 await testRunner.ThenAsync("the response code equals \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 134
 await testRunner.AndAsync("the response indicates success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
 await testRunner.WhenAsync("the response body is stored in variable \'deleteResult\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 137
 await testRunner.ThenAsync("the value of JSONPath \'$.message\' in variable \'deleteResult\' contains \'has been d" +
                        "eleted\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 138
 await testRunner.AndAsync("the value of JSONPath \'$.message\' in variable \'deleteResult\' contains \'id = $(cre" +
                        "atedId)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Non-success response")]
        public async global::System.Threading.Tasks.Task Non_SuccessResponse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Non-success response", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 141
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 142
 await testRunner.GivenAsync("the base URL \'$(demoApiBaseUrl)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 144
 await testRunner.WhenAsync("a \'GET\' request to \'/objects/99999999\' is made", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 145
 await testRunner.ThenAsync("the response does not indicate success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 146
 await testRunner.AndAsync("the response code does not equal \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Downloading a stream")]
        public async global::System.Threading.Tasks.Task DownloadingAStream()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Downloading a stream", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 149
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 150
 await testRunner.GivenAsync("the base URL \'$(demoApiBaseUrl)\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 152
 await testRunner.WhenAsync("a request to \'/cat\' is made", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 153
 await testRunner.AndAsync("the length of the response stream is stored in variable \'streamLength\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
 await testRunner.ThenAsync("the response code equals \'200\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 155
 await testRunner.AndAsync("the value of variable \'streamLength\' is greater than \'0\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 157
 await testRunner.WhenAsync("the response stream is saved to file \'cat.jpg\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 158
 await testRunner.AndAsync("the value of header \'Server\' is stored in variable \'serverHeader\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
 await testRunner.ThenAsync("the value of variable \'serverHeader\' equals \'Kestrel\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
